name: app_chat

packages:
  - "*"

scripts:
  build-resources:
    run: melos exec --fail-fast --scope="*resources*" --flutter -- flutter packages pub run build_runner build --delete-conflicting-outputs
    description: Generates assets resource.

  gen-app-icon:
    run: melos exec --fail-fast --scope="*resources*" --flutter -- flutter pub run flutter_launcher_icons
    description: Generates Resources resource app icon.

  gen-app-splash:
    run: melos exec --fail-fast --scope="*resources*" --flutter -- flutter pub run flutter_native_splash:create --flavor $1
    description: Generates Resources resource splash screen.

  gen-strings:
    run: melos exec --fail-fast --scope="*resources*" --flutter -- flutter pub run intl_utils:generate
    description: Generates strings resource.