// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAVseA7kzuN4YGp0hrWhy5oZvd3S-h998',
    appId: '1:739464888693:web:b97000484dfec05e05133c',
    messagingSenderId: '739464888693',
    projectId: 'appchatphone',
    authDomain: 'appchatphone.firebaseapp.com',
    storageBucket: 'appchatphone.appspot.com',
    measurementId: 'G-GC67Y4GNP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8waKP_fTRZ-_1WUmhmEOoZ2x_WrwbrMo',
    appId: '1:739464888693:android:dfd77b003daa60e305133c',
    messagingSenderId: '739464888693',
    projectId: 'appchatphone',
    storageBucket: 'appchatphone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkzxVnIVTc9wtKe-DH82c2jadGJp5Kbmk',
    appId: '1:739464888693:ios:e7457a11cd40c0c605133c',
    messagingSenderId: '739464888693',
    projectId: 'appchatphone',
    storageBucket: 'appchatphone.appspot.com',
    iosBundleId: 'com.example.appChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkzxVnIVTc9wtKe-DH82c2jadGJp5Kbmk',
    appId: '1:739464888693:ios:aebc54492bcc3dc505133c',
    messagingSenderId: '739464888693',
    projectId: 'appchatphone',
    storageBucket: 'appchatphone.appspot.com',
    iosBundleId: 'com.example.appChat.RunnerTests',
  );
}
